# Generated by Django 5.1.13 on 2025-10-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formpage',
            name='form_url',
            field=models.URLField(max_length=512, verbose_name='form url'),
        ),
    ]
