# Generated by Django 3.2.13 on 2022-04-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formpage',
            name='url',
        ),
        migrations.AddField(
            model_name='formpage',
            name='form_url',
            field=models.URLField(default='blah', verbose_name='form_url'),
            preserve_default=False,
        ),
    ]
