# Generated by Django 3.2.13 on 2022-04-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20220423_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='height',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='formpage',
            name='form_url',
            field=models.URLField(verbose_name='form url'),
        ),
    ]
