services:
  # Django
  web:
    depends_on:
      - s3
    env_file: ./config/.dev.env

  # Storage
  s3:
    image: bitnami/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - s3:/minio
    env_file: ./config/.dev.env
    hostname: s3.${POLREV_DOMAIN}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.s3.rule=Host(`s3.${POLREV_DOMAIN}`)"
      - "traefik.http.routers.s3.entrypoints=web"

  # Database Admin
  dbadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    restart: "no"
    ports:
        - "4444:80"
    env_file: ./config/.dev.env
    volumes:
        - dbadmin:/var/lib/pgadmin4/storage
    networks:
      - polrev

  # Mail
  maildev:
    image: maildev/maildev
    restart: "no"
    ports:
      - "1080:1080"
      - "1025:1025"
    env_file: ./config/.dev.env
    volumes:
      - maildev:/var/lib/maildev
    networks:
      - polrev

  traefik:
    ports:
      - "8888:80"
      - "8080:8080"

volumes:
  s3:
  dbadmin:
  maildev:
