# Copy to docker-compose.override.yml

services:
  # Django
  web:
    build:
      target: development

    depends_on:
      - s3
    environment:
      DJANGO_ENV: production
      AWS_S3_ENDPOINT_URL: http://${DOCKER_GATEWAY_HOST:-host.docker.internal}:9000
      #AWS_S3_ENDPOINT_URL: http://s3.${POLREV_DOMAIN}:9000
    env_file: .env
    labels:
      - "traefik.http.routers.web.rule=Host(`django.${POLREV_DOMAIN}`)"

  # Database
  db:
    env_file: .env

  redis:
    env_file: .env

  celery:
    build:
      target: development
    depends_on:
      - s3
    env_file: .env
    environment:
      AWS_S3_ENDPOINT_URL: http://${DOCKER_GATEWAY_HOST:-host.docker.internal}:9000
      #AWS_S3_ENDPOINT_URL: http://s3.${POLREV_DOMAIN}:9000

  celery-beat:
    build:
      target: development
    depends_on:
      - s3
    env_file: .env
    environment:
      AWS_S3_ENDPOINT_URL: http://${DOCKER_GATEWAY_HOST:-host.docker.internal}:9000
      #AWS_S3_ENDPOINT_URL: http://s3.${POLREV_DOMAIN}:9000

  # Traffic
  traefik:
    env_file: .env
    ports:
      - "8888:80"
      - "8080:8080"

  # Storage
  s3:
    image: bitnami/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - s3:/data
      - ./init-folders.sh:/init-folders.sh
    env_file: .env
    hostname: s3.${POLREV_DOMAIN}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.s3.rule=Host(`s3.${POLREV_DOMAIN}`)"
      - "traefik.http.routers.s3.entrypoints=web"
    command: |
      sh -c "
      /init-folders.sh && 
      /opt/bitnami/scripts/minio/run.sh"

  # Database Admin
  dbadmin:
    image: dpage/pgadmin4:latest
    depends_on:
      - db
    ports:
        - "4444:80"
    env_file: .env
    hostname: dbadmin.${POLREV_DOMAIN}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dbadmin.rule=Host(`dbadmin.${POLREV_DOMAIN}`)"
      - "traefik.http.routers.dbadmin.entrypoints=web"

    volumes:
        - dbadmin:/var/lib/pgadmin4/storage
    networks:
      - polrev

volumes:
  s3:
  dbadmin:
  maildev:
