services:

  # Django
  web:
    build:
      context: ./polrev
    depends_on:
      - db
    env_file: ./config/.dev.env
    environment:
      - IN_DOCKER=true
    hostname: django.${POLREV_DOMAIN}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`django.${POLREV_DOMAIN}`)"
      - "traefik.http.routers.web.entrypoints=web"
      #- "traefik.http.routers.web.tls=true"
    ports:
      - 8000:8000
    networks:
      - polrev
    volumes:
      - "./polrev:/app"

  # Database
  db:
    image: postgres:14.1
    env_file: ./config/.dev.env
    environment:
      - PGDATA=/pg-data
    ports:
      - 5432:5432
    volumes:
      - db:/pg-data
    networks:
      - polrev

  # Traffic
  traefik:
    image: "traefik:v2.5.4"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - --entrypoints.web-secure.address=:443
    labels:
      - "traefik.http.middlewares.test-compress.compress=true"
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - polrev

volumes:
  db:

networks:
  polrev: