services:

  # Django
  web:
    env_file: ./config/.prod.env
    restart: always
    labels:
      - "traefik.http.routers.web.rule=Host(`${POLREV_DOMAIN}`)"
      - traefik.http.routers.web.tls=true
      - traefik.http.routers.web.tls.certresolver=le

  # Database
  db:
    env_file: ./config/.prod.env
    restart: always

  traefik:
    env_file: ./config/.prod.env
    restart: always
