services:

  # Django
  web:
    env_file: ./config/.prod.env
    restart: always

  # Database
  db:
    env_file: ./config/.prod.env
    restart: always

  traefik:
    env_file: ./config/.prod.env
    restart: always
