volumes:
  dbadmin:
  maildev:

services:
  # Database Admin
  dbadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    restart: "no"
    ports:
        - "4444:80"
    env_file: ./config/.dev.env
    volumes:
        - dbadmin:/var/lib/pgadmin4/storage
    networks:
      - polrev

  # Mail
  maildev:
    image: maildev/maildev
    restart: "no"
    ports:
      - "1080:1080"
      - "1025:1025"
    volumes:
      - maildev:/var/lib/maildev
    networks:
      - polrev

  traefik:
    ports:
      - "8888:80"
      - "8080:8080"
