# Generated by Django 3.2.12 on 2022-03-15 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0016_schooldistrict'),
        ('offices', '0001_initial'),
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatepage',
            name='office_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidates', to='offices.office'),
        ),
        migrations.AddField(
            model_name='candidatepage',
            name='office_type_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidates', to='offices.officetype', verbose_name='office type'),
        ),
        migrations.AddField(
            model_name='statecandidatepagebase',
            name='state_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='state_candidates', to='areas.state', verbose_name='state'),
        ),
        migrations.CreateModel(
            name='UsSenateCandidatePage',
            fields=[
                ('statecandidatepagebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='candidates.statecandidatepagebase')),
                ('us_senate_office_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='us_senate_candidates', to='offices.ussenateoffice', verbose_name='office')),
            ],
            options={
                'verbose_name': 'US Senate Candidate',
            },
            bases=('candidates.statecandidatepagebase',),
        ),
        migrations.CreateModel(
            name='UsHouseCandidatePage',
            fields=[
                ('statecandidatepagebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='candidates.statecandidatepagebase')),
                ('district_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='us_house_candidates', to='areas.congressionaldistrict', verbose_name='district')),
                ('us_house_office_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='us_house_candidates', to='offices.ushouseoffice', verbose_name='office')),
            ],
            options={
                'verbose_name': 'US House Candidate',
            },
            bases=('candidates.statecandidatepagebase',),
        ),
        migrations.CreateModel(
            name='StateSenateCandidatePage',
            fields=[
                ('statecandidatepagebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='candidates.statecandidatepagebase')),
                ('district_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='state_senate_candidates', to='areas.statesenatedistrict', verbose_name='district')),
                ('state_senate_office_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='state_senate_candidates', to='offices.statesenateoffice', verbose_name='office')),
            ],
            options={
                'verbose_name': 'State Senate Candidate',
            },
            bases=('candidates.statecandidatepagebase',),
        ),
        migrations.CreateModel(
            name='StateHouseCandidatePage',
            fields=[
                ('statecandidatepagebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='candidates.statecandidatepagebase')),
                ('district_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='state_house_candidates', to='areas.statehousedistrict')),
                ('state_house_office_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='state_house_candidates', to='offices.statehouseoffice', verbose_name='office')),
            ],
            options={
                'verbose_name': 'State House Candidate',
            },
            bases=('candidates.statecandidatepagebase',),
        ),
        migrations.CreateModel(
            name='SchoolDistrictCandidatePage',
            fields=[
                ('statecandidatepagebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='candidates.statecandidatepagebase')),
                ('district_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='school_district_candidates', to='areas.schooldistrict')),
                ('school_district_office_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='school_district_candidates', to='offices.schooldistrictoffice', verbose_name='office')),
            ],
            options={
                'verbose_name': 'School District Candidate',
            },
            bases=('candidates.statecandidatepagebase',),
        ),
        migrations.CreateModel(
            name='LocalCouncilCandidatePage',
            fields=[
                ('statecandidatepagebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='candidates.statecandidatepagebase')),
                ('district_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='local_council_candidates', to='areas.localcouncildistrict', verbose_name='district')),
                ('local_council_office_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='local_council_candidates', to='offices.localcounciloffice', verbose_name='office')),
                ('place_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='local_council_candidates', to='areas.place', verbose_name='place')),
            ],
            options={
                'verbose_name': 'Local Council Candidate',
            },
            bases=('candidates.statecandidatepagebase',),
        ),
        migrations.CreateModel(
            name='LocalCandidatePage',
            fields=[
                ('statecandidatepagebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='candidates.statecandidatepagebase')),
                ('local_office_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='local_candidates', to='offices.localoffice', verbose_name='office')),
                ('place_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='local_candidates', to='areas.place')),
            ],
            options={
                'verbose_name': 'Local Candidate',
            },
            bases=('candidates.statecandidatepagebase',),
        ),
        migrations.CreateModel(
            name='CountyCouncilCandidatePage',
            fields=[
                ('statecandidatepagebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='candidates.statecandidatepagebase')),
                ('county_council_office_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='county_council_candidates', to='offices.countycounciloffice', verbose_name='office')),
                ('county_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='county_council_candidates', to='areas.county', verbose_name='county')),
                ('district_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='county_council_candidates', to='areas.countycouncildistrict', verbose_name='district')),
            ],
            options={
                'verbose_name': 'County Council Candidate',
            },
            bases=('candidates.statecandidatepagebase',),
        ),
        migrations.CreateModel(
            name='CountyCandidatePage',
            fields=[
                ('statecandidatepagebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='candidates.statecandidatepagebase')),
                ('county_office_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='county_candidates', to='offices.countyoffice', verbose_name='office')),
                ('county_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='county_candidates', to='areas.county', verbose_name='county')),
            ],
            options={
                'verbose_name': 'County Candidate',
            },
            bases=('candidates.statecandidatepagebase',),
        ),
    ]
