# Generated by Django 3.2.12 on 2022-03-15 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0002_stateoffice'),
        ('candidates', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateCandidatePage',
            fields=[
                ('statecandidatepagebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='candidates.statecandidatepagebase')),
                ('state_office_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='state_candidates', to='offices.stateofficebase', verbose_name='office')),
            ],
            options={
                'verbose_name': 'State Candidate',
            },
            bases=('candidates.statecandidatepagebase',),
        ),
    ]
