# Generated by Django 3.2.11 on 2022-02-14 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0001_initial'),
        ('candidates', '0002_auto_20220202_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatepage',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='states.statepage'),
        ),
    ]
