# Generated by Django 3.2.12 on 2022-04-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_statecandidatepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatepage',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='candidatepage',
            name='ballotpedia',
            field=models.URLField(blank=True, verbose_name='ballotpedia'),
        ),
        migrations.AddField(
            model_name='candidatepage',
            name='donate',
            field=models.URLField(blank=True, verbose_name='donate'),
        ),
        migrations.AddField(
            model_name='candidatepage',
            name='wikipedia',
            field=models.URLField(blank=True, verbose_name='wikipedia'),
        ),
    ]
