# Generated by Django 3.2.13 on 2022-04-30 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_fips', models.CharField(choices=[('01', 'Alabama'), ('02', 'Alaska'), ('04', 'Arizona'), ('05', 'Arkansas'), ('06', 'California'), ('08', 'Colorado'), ('09', 'Connecticut'), ('10', 'Delaware'), ('12', 'Florida'), ('13', 'Georgia'), ('15', 'Hawaii'), ('16', 'Idaho'), ('17', 'Illinois'), ('18', 'Indiana'), ('19', 'Iowa'), ('20', 'Kansas'), ('21', 'Kentucky'), ('22', 'Louisiana'), ('23', 'Maine'), ('24', 'Maryland'), ('25', 'Massachusetts'), ('26', 'Michigan'), ('27', 'Minnesota'), ('28', 'Mississippi'), ('29', 'Missouri'), ('30', 'Montana'), ('31', 'Nebraska'), ('32', 'Nevada'), ('33', 'New Hampshire'), ('34', 'New Jersey'), ('35', 'New Mexico'), ('36', 'New York'), ('37', 'North Carolina'), ('38', 'North Dakota'), ('39', 'Ohio'), ('40', 'Oklahoma'), ('41', 'Oregon'), ('42', 'Pennsylvania'), ('44', 'Rhode Island'), ('45', 'South Carolina'), ('46', 'South Dakota'), ('47', 'Tennessee'), ('48', 'Texas'), ('49', 'Utah'), ('50', 'Vermont'), ('51', 'Virginia'), ('53', 'Washington'), ('54', 'West Virginia'), ('55', 'Wisconsin'), ('56', 'Wyoming'), ('60', 'American Samoa'), ('66', 'Guam'), ('69', 'Northern Mariana Islands'), ('72', 'Puerto Rico'), ('78', 'Virgin Islands'), ('11', 'District of Columbia'), (None, 'Philippine Islands')], default='00', help_text='Example: 01, 02 ... 50', max_length=2, verbose_name='State FIPS')),
                ('title', models.CharField(help_text='Example: U.S. Senate, Ohio', max_length=256, verbose_name='title')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('area_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offices', to='areas.area', verbose_name='Area')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='OfficeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Example: U.S. Senate, State House, Mayor, City Council', max_length=256, verbose_name='title')),
                ('priority', models.PositiveSmallIntegerField(default=1000, help_text='Sorting priority.  Example: 0, 100, etc')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='FederalOffice',
            fields=[
                ('office_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='offices.office')),
            ],
            bases=('offices.office',),
        ),
        migrations.CreateModel(
            name='StateOfficeBase',
            fields=[
                ('office_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='offices.office')),
                ('state_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='state_offices', to='areas.state', verbose_name='state')),
            ],
            bases=('offices.office',),
        ),
        migrations.AddField(
            model_name='office',
            name='type_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offices', to='offices.officetype', verbose_name='Office Type'),
        ),
        migrations.CreateModel(
            name='StateOffice',
            fields=[
                ('stateofficebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='offices.stateofficebase')),
            ],
            options={
                'verbose_name': 'State Office',
            },
            bases=('offices.stateofficebase',),
        ),
        migrations.CreateModel(
            name='UsSenateOffice',
            fields=[
                ('stateofficebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='offices.stateofficebase')),
            ],
            options={
                'verbose_name': 'US Senate Office',
            },
            bases=('offices.stateofficebase',),
        ),
        migrations.CreateModel(
            name='UsHouseOffice',
            fields=[
                ('stateofficebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='offices.stateofficebase')),
                ('district_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='us_house_offices', to='areas.congressionaldistrict')),
            ],
            options={
                'verbose_name': 'US House Office',
            },
            bases=('offices.stateofficebase',),
        ),
        migrations.CreateModel(
            name='StateSenateOffice',
            fields=[
                ('stateofficebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='offices.stateofficebase')),
                ('district_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='state_senate_offices', to='areas.statesenatedistrict')),
            ],
            options={
                'verbose_name': 'State Senate Office',
            },
            bases=('offices.stateofficebase',),
        ),
        migrations.CreateModel(
            name='StateHouseOffice',
            fields=[
                ('stateofficebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='offices.stateofficebase')),
                ('district_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='state_house_offices', to='areas.statehousedistrict')),
            ],
            options={
                'verbose_name': 'State House Office',
            },
            bases=('offices.stateofficebase',),
        ),
        migrations.CreateModel(
            name='SchoolDistrictOffice',
            fields=[
                ('stateofficebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='offices.stateofficebase')),
                ('district_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='school_district_offices', to='areas.schooldistrict', verbose_name='district')),
            ],
            options={
                'verbose_name': 'School District Office',
            },
            bases=('offices.stateofficebase',),
        ),
    ]
