# Generated by Django 3.2.12 on 2022-03-15 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateOffice',
            fields=[
                ('stateofficebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='offices.stateofficebase')),
            ],
            options={
                'verbose_name': 'State Office',
            },
            bases=('offices.stateofficebase',),
        ),
    ]
