# Generated by Django 3.2.13 on 2022-04-23 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='subtitle',
        ),
    ]
