# Generated by Django 3.2.13 on 2022-04-30 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
        ('offices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountyOfficeBase',
            fields=[
                ('stateofficebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='offices.stateofficebase')),
                ('county_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='county_offices', to='areas.county', verbose_name='county')),
            ],
            bases=('offices.stateofficebase',),
        ),
        migrations.CreateModel(
            name='LocalOfficeBase',
            fields=[
                ('stateofficebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='offices.stateofficebase')),
                ('place_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='local_offices', to='areas.place', verbose_name='place')),
            ],
            bases=('offices.stateofficebase',),
        ),
        migrations.CreateModel(
            name='CountyOffice',
            fields=[
                ('countyofficebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='offices.countyofficebase')),
            ],
            options={
                'verbose_name': 'County Office',
            },
            bases=('offices.countyofficebase',),
        ),
        migrations.CreateModel(
            name='LocalOffice',
            fields=[
                ('localofficebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='offices.localofficebase')),
            ],
            options={
                'verbose_name': 'Local Office',
            },
            bases=('offices.localofficebase',),
        ),
        migrations.CreateModel(
            name='LocalCouncilOffice',
            fields=[
                ('localofficebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='offices.localofficebase')),
                ('district_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='local_council_offices', to='areas.localcouncildistrict', verbose_name='district')),
            ],
            options={
                'verbose_name': 'Local Council Office',
            },
            bases=('offices.localofficebase',),
        ),
        migrations.CreateModel(
            name='CountyCouncilOffice',
            fields=[
                ('countyofficebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='offices.countyofficebase')),
                ('district_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='county_council_offices', to='areas.countycouncildistrict', verbose_name='district')),
            ],
            options={
                'verbose_name': 'County Council Office',
            },
            bases=('offices.countyofficebase',),
        ),
    ]
