# Generated by Django 3.2.13 on 2022-05-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0002_countycounciloffice_countyoffice_countyofficebase_localcounciloffice_localoffice_localofficebase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='officetype',
            old_name='priority',
            new_name='rank',
        ),
        migrations.AddField(
            model_name='office',
            name='number',
            field=models.PositiveSmallIntegerField(default=1000, help_text='Sorting priority.  Example: 0, 100, etc'),
        ),
    ]
