# Generated by Django 3.2.13 on 2022-04-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0002_remove_office_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='officetype',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0, help_text='Sorting priority.  Example: 0, 100, etc'),
        ),
    ]
