# Generated by Django 3.2.13 on 2022-05-01 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0003_auto_20220501_2110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='officetype',
            options={'ordering': ['rank']},
        ),
        migrations.RemoveField(
            model_name='office',
            name='number',
        ),
    ]
