# Generated by Django 3.2.13 on 2022-04-24 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0003_officetype_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officetype',
            name='priority',
            field=models.PositiveSmallIntegerField(default=1000, help_text='Sorting priority.  Example: 0, 100, etc'),
        ),
    ]
