# Generated by Django 3.2.13 on 2022-05-02 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0005_office_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='office',
            options={'ordering': ['state_fips', 'number']},
        ),
    ]
