# Generated by Django 3.2.13 on 2022-05-02 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_statejudicialdistrict'),
        ('offices', '0006_alter_office_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateJudicialDistrictOffice',
            fields=[
                ('stateofficebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='offices.stateofficebase')),
                ('district_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='state_judicial_district_offices', to='areas.statejudicialdistrict', verbose_name='district')),
            ],
            options={
                'verbose_name': 'State Judicial District Office',
            },
            bases=('offices.stateofficebase',),
        ),
    ]
