# Generated by Django 3.2.12 on 2022-02-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joyous', '0018_auto_20220121_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closedfor',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
