# Generated by Django 3.2.13 on 2022-04-18 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birdsong', '0001_initial'),
        ('mailer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
