# Generated by Django 3.2.13 on 2022-04-30 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0002_countycounciloffice_countyoffice_countyofficebase_localcounciloffice_localoffice_localofficebase'),
        ('areas', '0001_initial'),
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountyCampaignPageBase',
            fields=[
                ('statecampaignpagebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='campaigns.statecampaignpagebase')),
                ('county_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='county_campaigns', to='areas.county', verbose_name='county')),
            ],
            options={
                'abstract': False,
            },
            bases=('campaigns.statecampaignpagebase',),
        ),
        migrations.CreateModel(
            name='LocalCampaignPageBase',
            fields=[
                ('statecampaignpagebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='campaigns.statecampaignpagebase')),
                ('place_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='local_campaigns', to='areas.place')),
            ],
            options={
                'abstract': False,
            },
            bases=('campaigns.statecampaignpagebase',),
        ),
        migrations.CreateModel(
            name='LocalCouncilCampaignPage',
            fields=[
                ('localcampaignpagebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='campaigns.localcampaignpagebase')),
                ('district_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='local_council_campaigns', to='areas.localcouncildistrict', verbose_name='district')),
                ('local_council_office_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='local_council_campaigns', to='offices.localcounciloffice', verbose_name='office')),
            ],
            options={
                'verbose_name': 'Local Council Campaign',
            },
            bases=('campaigns.localcampaignpagebase',),
        ),
        migrations.CreateModel(
            name='LocalCampaignPage',
            fields=[
                ('localcampaignpagebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='campaigns.localcampaignpagebase')),
                ('local_office_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='local_campaigns', to='offices.localoffice', verbose_name='office')),
            ],
            options={
                'verbose_name': 'Local Campaign',
            },
            bases=('campaigns.localcampaignpagebase',),
        ),
        migrations.CreateModel(
            name='CountyCouncilCampaignPage',
            fields=[
                ('countycampaignpagebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='campaigns.countycampaignpagebase')),
                ('county_council_office_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='county_council_campaigns', to='offices.countycounciloffice', verbose_name='office')),
                ('district_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='county_council_campaigns', to='areas.countycouncildistrict', verbose_name='district')),
            ],
            options={
                'verbose_name': 'County Council Campaign',
            },
            bases=('campaigns.countycampaignpagebase',),
        ),
        migrations.CreateModel(
            name='CountyCampaignPage',
            fields=[
                ('countycampaignpagebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='campaigns.countycampaignpagebase')),
                ('county_office_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='county_campaigns', to='offices.countyoffice', verbose_name='office')),
            ],
            options={
                'verbose_name': 'County Campaign',
            },
            bases=('campaigns.countycampaignpagebase',),
        ),
    ]
