# Generated by Django 3.2.13 on 2022-04-18 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ushousecampaignpage',
            options={'verbose_name': 'U.S. House Campaign'},
        ),
        migrations.AlterModelOptions(
            name='ussenatecampaignpage',
            options={'verbose_name': 'U.S. Senate Campaign'},
        ),
    ]
