# Generated by Django 3.2.12 on 2022-04-05 13:43

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
        ('campaigns', '0002_auto_20220405_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignspage',
            name='endorsements',
        ),
        migrations.RemoveField(
            model_name='campaignspage',
            name='parties',
        ),
        migrations.AddField(
            model_name='campaignpage',
            name='endorsements',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='endorsed_campaigns', to='parties.Party'),
        ),
        migrations.AddField(
            model_name='campaignpage',
            name='parties',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='campaigns', to='parties.Party'),
        ),
    ]
