# Generated by Django 3.2.13 on 2022-05-02 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0007_statejudicialdistrictoffice'),
        ('areas', '0002_statejudicialdistrict'),
        ('campaigns', '0002_countycampaignpage_countycampaignpagebase_countycouncilcampaignpage_localcampaignpage_localcampaignp'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateJudicialDistrictCampaignPage',
            fields=[
                ('statecampaignpagebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='campaigns.statecampaignpagebase')),
                ('district_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='state_judicial_district_campaigns', to='areas.statejudicialdistrict')),
                ('state_judicial_district_office_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='state_judicial_district_campaigns', to='offices.statejudicialdistrictoffice', verbose_name='office')),
            ],
            options={
                'verbose_name': 'State Judicial District Campaign',
            },
            bases=('campaigns.statecampaignpagebase',),
        ),
    ]
