# Generated by Django 3.2.13 on 2022-04-24 03:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_auto_20220418_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignpage',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Election date'),
        ),
    ]
