# Generated by Django 3.2.12 on 2022-04-17 09:02

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_auto_20220405_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignpage',
            name='parties',
        ),
        migrations.AddField(
            model_name='campaignpage',
            name='excerpt',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Entry excerpt to be displayed on entries list. If this field is not filled, a truncated version of body text will be used.', verbose_name='excerpt'),
        ),
    ]
