# Generated by Django 3.2.13 on 2022-05-06 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_statejudicialdistrictcampaignpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignspage',
            name='year_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='campaigns.yearpage'),
        ),
    ]
