# Generated by Django 3.2.12 on 2022-02-24 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Example: Mobile, Alabama', max_length=256, verbose_name='name')),
                ('name', models.CharField(help_text='Example: United States, Alabama, Mobile', max_length=64, verbose_name='name')),
                ('state_usps', models.CharField(default='US', help_text='Example: AL, AK ... WY', max_length=2, verbose_name='State USPS Code')),
                ('state_fips', models.CharField(default='00', help_text='Example: 01, 02 ... 50', max_length=2, verbose_name='State FIPS Code')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='image')),
            ],
        ),
    ]
