# Generated by Django 3.2.12 on 2022-02-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='state_usps',
        ),
        migrations.AddField(
            model_name='area',
            name='gnis_feature_id',
            field=models.CharField(blank=True, help_text='Example: 01779775', max_length=8, verbose_name='GNIS Feature Id'),
        ),
    ]
