# Generated by Django 3.2.12 on 2022-03-02 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_auto_20220224_0800'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegislativeDistrict',
            fields=[
                ('area_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='areas.area')),
                ('district_num', models.PositiveSmallIntegerField()),
                ('seats', models.PositiveSmallIntegerField()),
            ],
            bases=('areas.area',),
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('area_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='areas.area')),
                ('state_usps', models.CharField(help_text='Example: AL, AK ... WY', max_length=2, verbose_name='State USPS Code')),
            ],
            bases=('areas.area',),
        ),
        migrations.RemoveField(
            model_name='area',
            name='image',
        ),
        migrations.CreateModel(
            name='CongressionalDistrict',
            fields=[
                ('area_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='areas.area')),
                ('cd_fips', models.CharField(help_text='Example: AL, AK ... WY', max_length=2, verbose_name='Congressional District Code')),
                ('cd_num', models.PositiveSmallIntegerField()),
                ('state_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='congressional_districts', to='areas.state', verbose_name='State')),
            ],
            bases=('areas.area',),
        ),
        migrations.CreateModel(
            name='StateSenateDistrict',
            fields=[
                ('legislativedistrict_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='areas.legislativedistrict')),
                ('state_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='state_senate_districts', to='areas.state', verbose_name='State')),
            ],
            bases=('areas.legislativedistrict',),
        ),
        migrations.CreateModel(
            name='StateHouseDistrict',
            fields=[
                ('legislativedistrict_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='areas.legislativedistrict')),
                ('state_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='state_house_districts', to='areas.state', verbose_name='State')),
            ],
            bases=('areas.legislativedistrict',),
        ),
    ]
