# Generated by Django 3.2.13 on 2022-04-28 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_alter_area_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='FederalCourt',
            fields=[
                ('area_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='areas.area')),
                ('number', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['number'],
            },
            bases=('areas.area',),
        ),
        migrations.CreateModel(
            name='PrecinctCourt',
            fields=[
                ('area_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='areas.area')),
                ('number', models.PositiveSmallIntegerField()),
                ('county_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='precinct_courts', to='areas.county', verbose_name='County')),
                ('state_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='precinct_courts', to='areas.state', verbose_name='State')),
            ],
            options={
                'ordering': ['number'],
            },
            bases=('areas.area',),
        ),
        migrations.CreateModel(
            name='DistrictCourt',
            fields=[
                ('area_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='areas.area')),
                ('number', models.PositiveSmallIntegerField()),
                ('state_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='district_courts', to='areas.state', verbose_name='State')),
            ],
            options={
                'ordering': ['number'],
            },
            bases=('areas.area',),
        ),
        migrations.CreateModel(
            name='CircuitCourt',
            fields=[
                ('area_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='areas.area')),
                ('number', models.PositiveSmallIntegerField()),
                ('state_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='circuit_courts', to='areas.state', verbose_name='State')),
            ],
            options={
                'ordering': ['number'],
            },
            bases=('areas.area',),
        ),
    ]
