# Generated by Django 3.2.13 on 2022-05-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_statejudicialdistrict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statejudicialdistrict',
            name='district_num',
            field=models.PositiveSmallIntegerField(verbose_name='district number'),
        ),
    ]
