# Generated by Django 3.2.12 on 2022-03-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0003_auto_20220302_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congressionaldistrict',
            name='cd_fips',
            field=models.CharField(help_text='Example: 01 ... 99', max_length=2, verbose_name='Congressional District Code'),
        ),
    ]
