# Generated by Django 3.2.12 on 2022-03-04 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0004_alter_congressionaldistrict_cd_fips'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('area_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='areas.area')),
                ('county_fips', models.CharField(help_text='Example: 001, 002 ...', max_length=3, verbose_name='County FIPS Code')),
                ('class_fips', models.CharField(help_text='Example: H1, H4 ...', max_length=2, verbose_name='County Class FIPS Code')),
                ('state_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counties', to='areas.state', verbose_name='State')),
            ],
            bases=('areas.area',),
        ),
    ]
