# Generated by Django 3.2.13 on 2022-04-28 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0004_auto_20220428_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateDistrictCourt',
            fields=[
                ('area_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='areas.area')),
                ('number', models.PositiveSmallIntegerField()),
                ('state_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='state_district_courts', to='areas.state', verbose_name='State')),
            ],
            options={
                'ordering': ['number'],
            },
            bases=('areas.area',),
        ),
        migrations.CreateModel(
            name='StateCircuitCourt',
            fields=[
                ('area_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='areas.area')),
                ('number', models.PositiveSmallIntegerField()),
                ('state_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='state_circuit_courts', to='areas.state', verbose_name='State')),
            ],
            options={
                'ordering': ['number'],
            },
            bases=('areas.area',),
        ),
        migrations.CreateModel(
            name='FederalDistrictCourt',
            fields=[
                ('area_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='areas.area')),
                ('number', models.PositiveSmallIntegerField()),
                ('state_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='federal_district_courts', to='areas.state', verbose_name='State')),
            ],
            options={
                'ordering': ['number'],
            },
            bases=('areas.area',),
        ),
    ]
