# Generated by Django 3.2.12 on 2022-03-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0005_county'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='area',
            name='kind',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
