# Generated by Django 3.2.13 on 2022-04-28 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_alter_campaignpage_date'),
        ('offices', '0004_alter_officetype_priority'),
        ('areas', '0005_federaldistrictcourt_statecircuitcourt_statedistrictcourt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='precinctcourt',
            name='area_ptr',
        ),
        migrations.RemoveField(
            model_name='precinctcourt',
            name='county_ref',
        ),
        migrations.RemoveField(
            model_name='precinctcourt',
            name='state_ref',
        ),
        migrations.RemoveField(
            model_name='statecircuitcourt',
            name='area_ptr',
        ),
        migrations.RemoveField(
            model_name='statecircuitcourt',
            name='state_ref',
        ),
        migrations.RemoveField(
            model_name='statedistrictcourt',
            name='area_ptr',
        ),
        migrations.RemoveField(
            model_name='statedistrictcourt',
            name='state_ref',
        ),
        migrations.DeleteModel(
            name='FederalDistrictCourt',
        ),
        migrations.DeleteModel(
            name='PrecinctCourt',
        ),
        migrations.DeleteModel(
            name='StateCircuitCourt',
        ),
        migrations.DeleteModel(
            name='StateDistrictCourt',
        ),
    ]
