# Generated by Django 3.2.13 on 2022-04-28 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0006_auto_20220428_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='kind',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Unknown'), (1, 'State'), (2, 'Congressional District'), (3, 'State Senate District'), (4, 'State House District'), (5, 'County'), (6, 'City'), (7, 'Town'), (8, 'Village'), (9, 'Township'), (10, 'Charter Township'), (11, 'Borough'), (12, 'City and Borough'), (13, 'Unified Government'), (14, 'Consolidate Government'), (15, 'Metropolitan Government'), (16, 'Urban County'), (17, 'City and County'), (18, 'Municipality'), (19, 'Corporation'), (20, 'Plantation'), (23, 'Unified School District'), (24, 'Elementary School District'), (25, 'Secondary School District'), (26, 'Federal Judicial Circuit'), (27, 'Federal Judicial District'), (28, 'State Judicial Circuit'), (29, 'State Judicial District'), (30, 'County Judicial Precinct')], default=0),
        ),
        migrations.CreateModel(
            name='StateDistrictCourt',
            fields=[
                ('area_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='areas.area')),
                ('number', models.PositiveSmallIntegerField()),
                ('state_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='state_judicial_districts', to='areas.state', verbose_name='State')),
            ],
            options={
                'ordering': ['number'],
            },
            bases=('areas.area',),
        ),
        migrations.CreateModel(
            name='PrecinctCourt',
            fields=[
                ('area_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='areas.area')),
                ('number', models.PositiveSmallIntegerField()),
                ('county_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='county_judicial_precincts', to='areas.county', verbose_name='County')),
                ('state_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='county_judicial_precincts', to='areas.state', verbose_name='State')),
            ],
            options={
                'ordering': ['number'],
            },
            bases=('areas.area',),
        ),
    ]
