# Generated by Django 3.2.12 on 2022-03-05 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0006_auto_20220305_0610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('area_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='areas.area')),
                ('place_fips', models.CharField(help_text='Example: 00123', max_length=5, verbose_name='Place FIPS Code')),
                ('counties', models.ManyToManyField(to='areas.County')),
                ('state_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='places', to='areas.state', verbose_name='State')),
            ],
            bases=('areas.area',),
        ),
    ]
