# Generated by Django 3.2.12 on 2022-03-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0007_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='title',
            field=models.CharField(help_text='Example: Mobile, Alabama', max_length=256, verbose_name='title'),
        ),
        migrations.DeleteModel(
            name='Place',
        ),
    ]
