# Generated by Django 3.2.13 on 2022-04-28 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_alter_campaignpage_date'),
        ('offices', '0004_alter_officetype_priority'),
        ('areas', '0007_auto_20220428_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statedistrictcourt',
            name='area_ptr',
        ),
        migrations.RemoveField(
            model_name='statedistrictcourt',
            name='state_ref',
        ),
        migrations.DeleteModel(
            name='PrecinctCourt',
        ),
        migrations.DeleteModel(
            name='StateDistrictCourt',
        ),
    ]
