# Generated by Django 3.2.13 on 2022-04-28 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0008_auto_20220428_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateJudicialDistrict',
            fields=[
                ('area_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='areas.area')),
                ('number', models.PositiveSmallIntegerField()),
                ('state_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='state_judicial_districts', to='areas.state', verbose_name='State')),
            ],
            options={
                'ordering': ['number'],
            },
            bases=('areas.area',),
        ),
        migrations.CreateModel(
            name='CountyJudicialPrecinct',
            fields=[
                ('area_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='areas.area')),
                ('number', models.PositiveSmallIntegerField()),
                ('county_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='county_judicial_precincts', to='areas.county', verbose_name='County')),
                ('state_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='county_judicial_precincts', to='areas.state', verbose_name='State')),
            ],
            options={
                'ordering': ['number'],
            },
            bases=('areas.area',),
        ),
    ]
