# Generated by Django 3.2.12 on 2022-03-11 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0010_auto_20220305_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalCouncilDistrict',
            fields=[
                ('area_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='areas.area')),
                ('place_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='local_council_districts', to='areas.place', verbose_name='Place')),
                ('state_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='local_council_districts', to='areas.state', verbose_name='State')),
            ],
            bases=('areas.area',),
        ),
    ]
