# Generated by Django 3.2.12 on 2022-03-12 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0011_localcouncildistrict'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountyCouncilDistrict',
            fields=[
                ('area_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='areas.area')),
                ('county_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='county_council_districts', to='areas.county', verbose_name='County')),
                ('state_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='county_council_districts', to='areas.state', verbose_name='State')),
            ],
            bases=('areas.area',),
        ),
    ]
