# Generated by Django 3.2.12 on 2022-03-13 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0012_countycouncildistrict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='kind',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Unknown'), (1, 'Congressional District'), (2, 'State Senate District'), (3, 'State House District'), (4, 'County'), (5, 'City'), (6, 'Town'), (7, 'Village'), (8, 'Township'), (9, 'Charter Township'), (10, 'Borough'), (11, 'City and Borough'), (12, 'Unified Government'), (13, 'Consolidate Government'), (14, 'Metropolitan Government'), (15, 'Urban County'), (16, 'City and County'), (17, 'Municipality'), (18, 'Corporation'), (19, 'Plantation'), (22, 'Unified')], default=0),
        ),
        migrations.CreateModel(
            name='SchoolDistrict',
            fields=[
                ('area_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='areas.area')),
                ('lea_code', models.CharField(help_text='Example: 00123', max_length=5, verbose_name='LEA Code')),
                ('state_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='school_districts', to='areas.state', verbose_name='State')),
            ],
            bases=('areas.area',),
        ),
    ]
