# Generated by Django 3.2.12 on 2022-03-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0013_auto_20220313_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='kind',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Unknown'), (1, 'Congressional District'), (2, 'State Senate District'), (3, 'State House District'), (4, 'County'), (5, 'City'), (6, 'Town'), (7, 'Village'), (8, 'Township'), (9, 'Charter Township'), (10, 'Borough'), (11, 'City and Borough'), (12, 'Unified Government'), (13, 'Consolidate Government'), (14, 'Metropolitan Government'), (15, 'Urban County'), (16, 'City and County'), (17, 'Municipality'), (18, 'Corporation'), (19, 'Plantation'), (22, 'Unified School District'), (23, 'Elementary School District'), (24, 'Secondary School District')], default=0),
        ),
    ]
