# Generated by Django 3.2.12 on 2022-03-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0014_alter_area_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(help_text='Example: United States, Alabama, Mobile', max_length=128, verbose_name='name'),
        ),
        migrations.DeleteModel(
            name='SchoolDistrict',
        ),
    ]
