# Generated by Django 3.2.12 on 2022-03-13 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0015_auto_20220313_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolDistrict',
            fields=[
                ('area_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='areas.area')),
                ('lea_code', models.CharField(help_text='Example: 00123', max_length=5, verbose_name='LEA Code')),
                ('state_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='school_districts', to='areas.state', verbose_name='State')),
            ],
            bases=('areas.area',),
        ),
    ]
