# Generated by Django 3.2.11 on 2022-01-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puput', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrypage',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
