# Generated by Django 5.1.4 on 2025-01-12 05:55

import django.db.models.deletion
import puput.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puput', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='main_color',
            field=puput.fields.ColorField(default='#4D6AE0', max_length=255, verbose_name='Blog Main Color'),
        ),
        migrations.AlterField(
            model_name='tagentrypage',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag'),
        ),
    ]
