# Generated by Django 5.1.6 on 2025-02-16 12:03

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infopage',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', 0), ('image', 1), ('markdown', 2), ('embed', 3), ('html', 4)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtailmarkdown.blocks.MarkdownBlock', (), {'icon': 'code'}), 3: ('wagtail.embeds.blocks.EmbedBlock', (), {'max_height': 400, 'max_width': 800}), 4: ('wagtail.blocks.RawHTMLBlock', (), {})}),
        ),
    ]
