# Generated by Django 3.2.13 on 2022-04-17 22:59

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='Example: Working Families Party', verbose_name='title')),
                ('abbrev', models.CharField(help_text='Example: WFP', max_length=16, verbose_name='abbreviation')),
                ('color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None)),
                ('website', models.URLField(blank=True, verbose_name='website')),
            ],
            options={
                'verbose_name_plural': 'Parties',
                'ordering': ['title'],
            },
        ),
    ]
